version: "3.8"
services:
  app:
    build:
      context: ./movie-list/frontend
    ports:
      - "80:8080" # Map Svelte app to port 80
      - "9229:9229"  # Expose debug port
    environment:
      - TARGET="${TARGET}"
    command: "npm run dev"
    # local endpoint variable
    volumes:
      - ./movie-list/frontend:/app # Mount local directory to /app in the container
      - /app/node_modules
    working_dir: /app # Set working directory to /app

  express-server:
    build:
      context: ./movie-list/backend
    ports:
      - "3000:3000" # Map express to port 3000
      - "9230:9229"  # Expose debug port (container's 9229 to host's 9230)
    command: "npm run dev"
    volumes:
      - ./movie-list/backend:/express-server # Mount local directory to /app in the container
      - /express-server/node_modules # Prevent overwriting node_modules
    working_dir: /express-server # Set working directory to /app
    restart: always

  mongodb_new:
    image: mongo:latest
    container_name: mongodb_new
    ports:
      - "27018:27017" # Expose new MongoDB on a different port
    volumes:
      - ./mongodb-data-new:/data/db
    command: ["mongod", "--replSet", "rs0"]
    # restart: always
    # limit memory usage to 500MB
    hostname: mongodb_new
    mem_limit: 1g

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13 # Choose your desired version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Set Java memory options
    ports:
      - "9200:9200" # Elasticsearch REST API
      - "9300:9300" # Elasticsearch transport protocol
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data # Persist data
    # restart: always
    mem_limit: 1g

  monstache:
    image: rwynn/monstache:latest
    container_name: monstache
    depends_on:
      - mongodb_new
      - elasticsearch
    environment:
    # MongoDB connection string
      - MONSTACHE_MONGO_URL=mongodb://admin:mypass@mongodb_new:27017
    # Elasticsearch connection string
      - MONSTACHE_ES_URL=http://elasticsearch:9200
    volumes:
      - ./monstache-config.toml:/config/monstache-config.toml # Mount configuration file
    command: ["-f", "/config/monstache-config.toml"] # Run with custom config
    mem_limit: 2g
