# MongoDB connection URI
mongo-url = "mongodb://admin:mypass@mongodb_new:27017/moviedb?authSource=admin"

# Elasticsearch connection URI
elasticsearch-urls = ["http://elasticsearch:9200"]

# Direct read all collections in the moviedb database
direct-read-namespaces = ["moviedb.movies"]

# Change stream for real-time sync of all collections in moviedb
change-stream-namespaces = ["moviedb"]

# Resume syncing on restart
resume = true
resume-name = "moviedb-sync"

# Enable gzip compression for Elasticsearch requests
gzip = true

verbose = true

# Prevent exit after syncing existing data
exit-after-direct-reads = false

